
package Fomularios;

import Metodos.ConexionBD;
import Metodos.MetodosSql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author José Pérez
 */
public class DetalleEgreso extends javax.swing.JFrame {

    /**
     * Creates new form DetalleEgreso
     */
    public DetalleEgreso() {
        initComponents();
        mostrarDatos();
//        icon_Formulario();
        setLocationRelativeTo(null);
//        BtnReporteFiltro.setVisible(false);
//        BtnReporteTotal.setVisible(false);

    }

    MetodosSql Met = new MetodosSql();
    ConexionBD cc = new ConexionBD();
    Connection con = ConexionBD.conectar();

//    public void icon_Formulario() {
//        //aca debemos importar la imagen de nuestra libreria 
//
//        URL url = getClass().getResource("/imagenes/logoico.png");
//        //Instanciamos ... 
//        ImageIcon icon_Formulario = new ImageIcon(url);
//        setIconImage(icon_Formulario.getImage());
//    }
    public void mostrarDatos() {
//CON ESTE METODO MOSTRAMOS EL CONTENIDO DE LA TABLA
String[] titulos = {"Hoja de Ing.", "Cod Mat", "Retirado por", "Sector y comentarios", "Ref.OT/MT/MG/MF", "Fecha", "Producto", "Medida", "Marca", "cantidad"};
String[] registros = new String[10];

DefaultTableModel modelo = new DefaultTableModel(null, titulos);

String SQL = "SELECT * FROM querico.detalleegreso";

try {
Statement st = con.createStatement();
ResultSet rs = st.executeQuery(SQL);

while (rs.next()) {

registros[0] = rs.getString("hoja");
registros[1] = rs.getString("cod");
registros[2] = rs.getString("retira");
registros[3] = rs.getString("sector");
registros[4] = rs.getString("ref");
registros[5] = rs.getString("fecha");
registros[6] = rs.getString("producto");
registros[7] = rs.getString("medida");
registros[8] = rs.getString("marca");
registros[9] = rs.getString("cantidad");

modelo.addRow(registros);

}
JTDetalleegreso.setModel(modelo);

} catch (Exception e) {
JOptionPane.showMessageDialog(null, "Error al monstrar el mensaje" + e);
}

}

    public void FiltrarDatos(String valor) {
//CON ESTE METODO PODEMOS FLITRAR BUSQUEDAS ESPECIFICAS
String[] titulos = {"Hoja de Ing.", "Cod Mat", "Retirado por", "Sector y comentarios", "Ref.OT/MT/MG/MF", "Fecha", "Producto", "Medida", "Marca", "cantidad"};
String[] registros = new String[10];

DefaultTableModel modelo = new DefaultTableModel(null, titulos);

//        String SQL = "SELECT * FROM labarrera.clientes WHERE CONCAT(cod,nombre,apellido,dni,direccion,ncalle,ecalle,telefono,celular,observaciones) LIKE '%" + valor + "%'";
String SQL = "SELECT * FROM querico.detalleegreso WHERE CONCAT(hoja,cod,retira,sector,ref,producto,cantidad) LIKE '%" + valor + "%'";

try {
Statement st = con.createStatement();
ResultSet rs = st.executeQuery(SQL);

while (rs.next()) {

    registros[0] = rs.getString("hoja");
    registros[1] = rs.getString("cod");
    registros[2] = rs.getString("retira");
    registros[3] = rs.getString("sector");
    registros[4] = rs.getString("ref");
    registros[5] = rs.getString("fecha");
    registros[6] = rs.getString("producto");
    registros[7] = rs.getString("medida");
    registros[8] = rs.getString("marca");
    registros[9] = rs.getString("cantidad");

    modelo.addRow(registros);

}
JTDetalleegreso.setModel(modelo);

} catch (Exception e) {
JOptionPane.showMessageDialog(null, "Error al monstrar el mensaje" + e);
}

    }

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDetalleegreso = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        RDHoja = new javax.swing.JRadioButton();
        BtnBuscar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RDSector = new javax.swing.JRadioButton();
        BtnBuscar1 = new javax.swing.JButton();
        BtnBorrar1 = new javax.swing.JButton();
        JCSectores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        BtnReporteTotal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle de Egreso");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETALLE DE EGRESOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        JTDetalleegreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTDetalleegreso.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(JTDetalleegreso);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N

        RDHoja.setText("Busqueda por Fechas");
        RDHoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDHojaActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnBorrar.setText("Limpiar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        jLabel5.setText("DESDE:");

        jLabel6.setText("HASTA:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RDHoja)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDHoja)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBorrar)
                    .addComponent(BtnBuscar))
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("DESDE:");

        jLabel3.setText("HASTA:");

        RDSector.setText("Busqueda sectores /Fechas");
        RDSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDSectorActionPerformed(evt);
            }
        });

        BtnBuscar1.setText("Buscar");
        BtnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscar1ActionPerformed(evt);
            }
        });

        BtnBorrar1.setText("Limpiar");
        BtnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrar1ActionPerformed(evt);
            }
        });

        JCSectores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Playa", "Desplume", "Eviscerado", "Chiller", "Empaque", "Tunel P", "Trozado", "Otros", " " }));

        jLabel4.setText("SECTOR: ");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(RDSector)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JCSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RDSector)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCSectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBorrar1)
                    .addComponent(BtnBuscar1))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnReporteTotal.setText("Reporte por Fecha");
        BtnReporteTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReporteTotalActionPerformed(evt);
            }
        });

        jButton2.setText("Reporte por Sector");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(BtnReporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReporteTotal)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnReporteTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReporteTotalActionPerformed
try {
//        

    String path = "C:\\NetBeansProjects\\QueRico\\src\\Reportes\\R_EgresoHoja.jasper";
    JasperReport reporte = null;

    reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
    Map parametros = new HashMap();

    Date fecha1 = jDateChooser4.getDate();
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
    String fec1 = "" + formatofecha.format(fecha1);
    Date fecha2 = jDateChooser3.getDate();
    SimpleDateFormat formatofecha2 = new SimpleDateFormat("dd/MM/yyyy");
    String fec2 = "" + formatofecha2.format(fecha2);
    parametros.put("f_ini", fec1);
    parametros.put("f_fin", fec2);

    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametros, con);

    JasperViewer view = new JasperViewer(jprint, false);

    view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    view.setVisible(true);

} catch (JRException ex) {
    Logger.getLogger(DetalleIngreso.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "No se encuentra reporte" + ex);
}
    }//GEN-LAST:event_BtnReporteTotalActionPerformed
//    public void FiltararHoja() {
//        String hoja1 = TxtHoja.getText();
//        String consulta = "";
//        consulta = "SELECT * FROM querico.detalleegreso WHERE hoja='" + hoja1 + "'";
//
//        String[] titulos = {"Hoja de Ing.", "Cod Mat", "Retirado por", "Sector y comentarios", "Ref.OT/MT/MG/MF", "Fecha", "Producto", "Medida", "Marca", "cantidad"};
//        String[] registros = new String[10];
//        DefaultTableModel tabla = new DefaultTableModel(null, titulos);
//
//        try {
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery(consulta);
//
//            while (rs.next()) {
//
//                registros[0] = rs.getString("hoja");
//                registros[1] = rs.getString("cod");
//                registros[2] = rs.getString("retira");
//                registros[3] = rs.getString("sector");
//                registros[4] = rs.getString("ref");
//                registros[5] = rs.getString("fecha");
//                registros[6] = rs.getString("producto");
//                registros[7] = rs.getString("medida");
//                registros[8] = rs.getString("marca");
//                registros[9] = rs.getString("cantidad");
//
//                tabla.addRow(registros);
//
//            }
//            JTDetalleegreso.setModel(tabla);
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error al monstrar el mensaje" + e);
//        }
//    }
    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed

        mostrarDatos();
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed

String consulta = "";
if (RDHoja.isSelected() == true) {

Date fecha1 = jDateChooser4.getDate();
SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");

String fec1 = "" + formatofecha.format(fecha1);

Date fecha2 = jDateChooser3.getDate();
SimpleDateFormat formatofecha2 = new SimpleDateFormat("dd/MM/yyyy");
String fec2 = "" + formatofecha2.format(fecha2);

consulta = "SELECT * FROM querico.detalleegreso WHERE fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";

String[] titulos = {"Hoja de Ing.", "Cod Mat", "Retirado por", "Sector y comentarios", "Ref.OT/MT/MG/MF", "Fecha", "Producto", "Medida", "Marca", "cantidad"};
String[] registros = new String[10];
DefaultTableModel tabla = new DefaultTableModel(null, titulos);

try {
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery(consulta);

    while (rs.next()) {

        registros[0] = rs.getString("hoja");
        registros[1] = rs.getString("cod");
        registros[2] = rs.getString("retira");
        registros[3] = rs.getString("sector");
        registros[4] = rs.getString("ref");
        registros[5] = rs.getString("fecha");
        registros[6] = rs.getString("producto");
        registros[7] = rs.getString("medida");
        registros[8] = rs.getString("marca");
        registros[9] = rs.getString("cantidad");

        tabla.addRow(registros);

    }
    JTDetalleegreso.setModel(tabla);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al monstrar el mensaje" + e);
}
} else {

JOptionPane.showMessageDialog(null, "Error!... llene todos los campos.");
}

    }//GEN-LAST:event_BtnBuscarActionPerformed


    private void RDHojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDHojaActionPerformed
if (RDHoja.isSelected() == true) {
    jDateChooser4.setEnabled(true);

    jDateChooser3.setEnabled(true);

    jDateChooser1.setEnabled(false);

    jDateChooser2.setEnabled(false);
    RDSector.setEnabled(false);
    BtnBorrar1.setEnabled(false);
    BtnBuscar1.setEnabled(false);
    JCSectores.setEnabled(false);

} else {

    jDateChooser1.setEnabled(true);

    jDateChooser2.setEnabled(true);
    RDSector.setEnabled(true);
    BtnBorrar1.setEnabled(true);
    BtnBuscar1.setEnabled(true);
    JCSectores.setEnabled(true);

}
    }//GEN-LAST:event_RDHojaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //REPORTE POR FILTROS
try {
    String path = "C:\\NetBeansProjects\\QueRico\\src\\Reportes\\R_EgresoSectoreFecha.jasper";

    JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
    Map parametros = new HashMap();

    parametros.put("sectores", JCSectores.getSelectedItem().toString());

    Date fecha1 = jDateChooser1.getDate();
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
    String fec1 = "" + formatofecha.format(fecha1);
    Date fecha2 = jDateChooser2.getDate();
    SimpleDateFormat formatofecha2 = new SimpleDateFormat("dd/MM/yyyy");
    String fec2 = "" + formatofecha2.format(fecha2);
    parametros.put("f_ini", fec1);
    parametros.put("f_fin", fec2);

    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametros, con);

    JasperViewer view = new JasperViewer(jprint, false);

    view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    view.setVisible(true);
} catch (JRException ex) {
    Logger.getLogger(DetalleIngreso.class.getName()).log(Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RDSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDSectorActionPerformed
if (RDSector.isSelected() == true) {
    jDateChooser1.setEnabled(true);
    jDateChooser2.setEnabled(true);
    BtnBuscar1.setEnabled(true);
    BtnBorrar1.setEnabled(true);
    JCSectores.setEnabled(true);
    RDSector.setEnabled(true);

    jDateChooser4.setEnabled(false);
    jDateChooser3.setEnabled(false);
    BtnBuscar.setEnabled(false);
    BtnBorrar.setEnabled(false);

} else {

    jDateChooser4.setEnabled(true);
    jDateChooser3.setEnabled(true);

    BtnBuscar.setEnabled(true);
    BtnBorrar.setEnabled(true);

}

    }//GEN-LAST:event_RDSectorActionPerformed

    private void BtnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscar1ActionPerformed
    String consulta = "";
    if (RDSector.isSelected() == true) {

    Date fecha1 = jDateChooser1.getDate();
    SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");

    String fec1 = "" + formatofecha.format(fecha1);

    Date fecha2 = jDateChooser2.getDate();
    SimpleDateFormat formatofecha2 = new SimpleDateFormat("dd/MM/yyyy");
    String fec2 = "" + formatofecha2.format(fecha2);

    consulta = "SELECT * FROM querico.detalleegreso WHERE fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";

    if (JCSectores.getSelectedItem().equals("Playa")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Playa' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Desplume")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Desplume' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "'";

    }
    if (JCSectores.getSelectedItem().equals("Eviscerado")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Eviscerado' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Chiller")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Chiller' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Empaque")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Empaque' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Tunel P")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Tunel P' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Trozado")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Trozado' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }
    if (JCSectores.getSelectedItem().equals("Otros")) {

    consulta = "SELECT * FROM querico.detalleegreso WHERE sector='Otros' AND fecha  BETWEEN '" + fec1 + "' AND '" + fec2 + "' ";
    }

    String[] titulos = {"Hoja de Ing.", "Cod Mat", "Retirado por", "Sector y comentarios", "Ref.OT/MT/MG/MF", "Fecha", "Producto", "Medida", "Marca", "cantidad"};
    String[] registros = new String[10];
    DefaultTableModel tabla = new DefaultTableModel(null, titulos);

    try {
    Statement st = con.createStatement();
    ResultSet rs = st.executeQuery(consulta);

    while (rs.next()) {

        registros[0] = rs.getString("hoja");
        registros[1] = rs.getString("cod");
        registros[2] = rs.getString("retira");
        registros[3] = rs.getString("sector");
        registros[4] = rs.getString("ref");
        registros[5] = rs.getString("fecha");
        registros[6] = rs.getString("producto");
        registros[7] = rs.getString("medida");
        registros[8] = rs.getString("marca");
        registros[9] = rs.getString("cantidad");

        tabla.addRow(registros);

    }
    JTDetalleegreso.setModel(tabla);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al monstrar el mensaje" + e);
            }
        }
    }//GEN-LAST:event_BtnBuscar1ActionPerformed

    private void BtnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrar1ActionPerformed
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        JCSectores.setSelectedItem("");
    }//GEN-LAST:event_BtnBorrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleEgreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleEgreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBorrar1;
    public static javax.swing.JButton BtnBuscar;
    public static javax.swing.JButton BtnBuscar1;
    private javax.swing.JButton BtnReporteTotal;
    private javax.swing.JComboBox<String> JCSectores;
    private javax.swing.JTable JTDetalleegreso;
    private javax.swing.JRadioButton RDHoja;
    private javax.swing.JRadioButton RDSector;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
