package Fomularios;

import java.awt.CardLayout;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author José Pérez
 */
public class Portal extends javax.swing.JFrame {

//    Panel_Reportes Reporte = new Panel_Reportes();
    Panel_Pañol Pañol = new Panel_Pañol();
    Panel_Manteniento Mantenimiento = new Panel_Manteniento();
    Panel_Produccion Produccion = new Panel_Produccion();
    CardLayout vistac;

    public Portal() {
        initComponents();

//        icon_Formulario();
        setLocationRelativeTo(null);

        vistac = (CardLayout) pnl_vista_principal.getLayout();
        FechaActual();
        run();
        //this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblNombreP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        BtnPañol = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        BtnProduccion = new javax.swing.JToggleButton();
        BtnMantenimiento = new javax.swing.JToggleButton();
        BtnaDesconectar = new javax.swing.JButton();
        pnl_vista_principal = new javax.swing.JPanel();
        JHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal Que Rico");
        setModalExclusionType(null);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel1.setText("Bienvenido : ");

        LblNombreP.setBackground(new java.awt.Color(255, 0, 0));
        LblNombreP.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        LblNombreP.setForeground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnRegistrar.setText("Registrar ");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        BtnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BtnRegistrarKeyReleased(evt);
            }
        });

        BtnPañol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pañol.png"))); // NOI18N
        BtnPañol.setText("PAÑOL");
        BtnPañol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnPañol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnPañol.setIconTextGap(25);
        BtnPañol.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BtnPañol.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPañol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPañolMouseClicked(evt);
            }
        });
        BtnPañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPañolActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        BtnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/produccion.png"))); // NOI18N
        BtnProduccion.setText("PRODUCCION");
        BtnProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnProduccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BtnProduccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProduccionActionPerformed(evt);
            }
        });

        BtnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.png"))); // NOI18N
        BtnMantenimiento.setText("MANTENIMIENTO");
        BtnMantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnMantenimiento.setInheritsPopupMenu(true);
        BtnMantenimiento.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BtnMantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMantenimientoActionPerformed(evt);
            }
        });

        BtnaDesconectar.setText("Desconectar");
        BtnaDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPañol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnaDesconectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnPañol, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BtnRegistrar)
                .addGap(18, 18, 18)
                .addComponent(BtnaDesconectar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pnl_vista_principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_vista_principal.setLayout(new java.awt.CardLayout());

        JHora.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel2.setText("Hora: ");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel3.setText("Fecha: ");

        JFecha.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        jLabel5.setText("Que Rico S.A");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Version 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JHora, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_vista_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LblNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JHora, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(1236, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        RegistroUsuarios ventana = new RegistroUsuarios();
        ventana.setVisible(true);


    }//GEN-LAST:event_BtnRegistrarActionPerformed
//public void icon_Formulario() {
//        //aca debemos importar la imagen de nuestra libreria 
//
//        URL url = getClass().getResource("/imagenes/logoico.png");
//        //Instanciamos ... 
//        ImageIcon icon_Formulario = new ImageIcon(url);
//        setIconImage(icon_Formulario.getImage());
//    }

    public void FechaActual() { //Metodo para mostara la fecha 

        LocalDateTime ahora = LocalDateTime.now();
        int año = ahora.getYear();
        int mes = ahora.getMonthValue();
        int dia = ahora.getDayOfMonth();

        JFecha.setText(dia + "/" + mes + "/" + año);
    }

    public void run() { //Metodo con hilos para actualizar la hora
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = () -> {
            while (true) {
                try {
                    Thread.sleep(500);
                    JHora.setText(formateador.format(LocalDateTime.now()));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnRegistrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnRegistrarKeyReleased
        //        String busqueda_usuario = Met.BuscarUsuarioRegistrado(TxtCorre.getText(), contraseña) , TxtContraseña.getText());


    }//GEN-LAST:event_BtnRegistrarKeyReleased

    private void BtnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProduccionActionPerformed
        if (BtnProduccion.isSelected()) {

            pnl_vista_principal.add(Produccion, "Produccion");
            vistac.show(pnl_vista_principal, "Produccion");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnPañol.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnMantenimiento.setEnabled(false);

            BtnProduccion.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnPañol.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnMantenimiento.setEnabled(true);
            BtnProduccion.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_BtnProduccionActionPerformed

    private void BtnPañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPañolActionPerformed

        if (BtnPañol.isSelected()) {

            pnl_vista_principal.add(Pañol, "Pañol");
            vistac.show(pnl_vista_principal, "Pañol");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnProduccion.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnMantenimiento.setEnabled(false);

            BtnPañol.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnProduccion.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnMantenimiento.setEnabled(true);
            BtnPañol.setBackground(new Color(204, 204, 204));

        }


    }//GEN-LAST:event_BtnPañolActionPerformed

    private void BtnPañolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPañolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPañolMouseClicked

    private void BtnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMantenimientoActionPerformed
        if (BtnMantenimiento.isSelected()) {

            pnl_vista_principal.add(Mantenimiento, "Mantenimiento");
            vistac.show(pnl_vista_principal, "Mantenimiento");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //ACTIVAMOS EL BOTON QUE PRESIONAMOS Y BLOQUEAMOS LOS DEMAS
            BtnProduccion.setEnabled(false);

//            BtnReportes.setEnabled(false);
            BtnPañol.setEnabled(false);

            BtnMantenimiento.setBackground(Color.WHITE);

        } else {
            //LIMPIAMOS LAS CAJAS DE LO CONTRARIO
            pnl_vista_principal.removeAll();
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            //Y ACTIVAMOS NUEVAMENTES LOS BOTONES Y DEVOLVEMOS EL COLOR AL BOTON 
            BtnProduccion.setEnabled(true);
//            BtnReportes.setEnabled(true);

            BtnPañol.setEnabled(true);
            BtnMantenimiento.setBackground(new Color(204, 204, 204));

        }
    }//GEN-LAST:event_BtnMantenimientoActionPerformed

    private void BtnaDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaDesconectarActionPerformed
        String eti;
        eti = LblNombreP.getText();
        JOptionPane.showMessageDialog(rootPane, "" + eti + " se desconecto del sistema!");
        InicioSesion ventana = new InicioSesion();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnaDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnMantenimiento;
    private javax.swing.JToggleButton BtnPañol;
    private javax.swing.JToggleButton BtnProduccion;
    public javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnaDesconectar;
    private javax.swing.JLabel JFecha;
    private javax.swing.JLabel JHora;
    public static javax.swing.JLabel LblNombreP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
